### ISSUE TITLE
Tower placement does not work

### ISSUE THREAD

**Issue by JulianStaab** [JulianStaab/MR-Card-Game#11]
Describe the bug
Since the redesign, when spawning new Towers into the game, the Towers are not placed correctly. Instead they are placed far off to the side of the board barely visible.

**To Reproduce**
1. Start the application.
2. Click on "Select Level".
3. Start a Level.
4. Hold a Tower card into the camera.
5. Click on "Build Tower".
6. Select a tower to build.
7. The tower will be barely visible in the distance when the game board is displayed.

**Expected behavior**
The tower should be built at the location of the Tower card.

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [x] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
Some missing references caused the problem to occur and has now been resolved.
