### ISSUE TITLE
Return to Menu after Defeat

### ISSUE THREAD

**Issue by JulianStaab** [JulianStaab/MR-Card-Game#6]
**Describe the bug**
After returning to the Main Menu from the Level, the Gallery page of the Lightning Strike is also enabled such that the Main Menu and Lightning Strike page are stacked over each other.

**To Reproduce**
1. Start a Level
2. Click on Return to Main Menu
3. In the Defeat Screen click on Return to Main Menu
4. See the Lightning Strike page over the Main Menu page

**Expected behavior**
The Lightning Strike page should not be open.

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [ ] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [x] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
The layer of the game board was incorrect. After setting it to "Map", both the enemy movement and the UI Bug after being defeated are resolved.
