### ISSUE TITLE
Enemies move only to certain waypoint

### ISSUE THREAD

**Issue by JulianStaab** [JulianStaab/MR-Card-Game#7]
Describe the bug
When starting the first wave of enemies in the game, the enemies will only move as far as a certain waypoint and not move any further.

**To Reproduce**
1. Start the application.
2. Click on "Select Level".
3. Start a Level.
4. Click on "Next Wave".
5. Enemies will start coming out of the portal but will only move to a waypoint between Waypoint04 to Waypoint07

**Expected behavior**
The enemies should continue to move along the path specified by the waypoints.

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [ ] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [x] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
The layer of the game board was incorrect. After setting it to "Map", both the enemy movement and the UI Bug after being defeated are resolved.
