### ISSUE TITLE
Cards cannot be played

### ISSUE THREAD

**Issue by JulianStaab** [JulianStaab/MR-Card-Game#8]
**Describe the bug**
After successfully answering a question, the respective spell card cannot be played. It does not display "Play Spell" neither is the button clickable.

**To Reproduce**
1. Start a Level
2. Hold a non-Tower, non-Trap card into the camera.
3. Click on "Draw Spell"
4. Correctly answer the question.
5. Hold the same card into the camera again.

**Expected behavior**
The text: "Play Spell" should be displayed on the card and the button should be clickable to execute the effect of the respective spell.

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [ ] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [x] Smartphone
- [ ] Other:

**Comment by EmilieHK** [comment]
This issue has been resolved for a handful of markers. However, not all markers trigger UI to be displayed. As we have observed the same issue on the main branch of the MR Card Game, this seems to be an issue unrelated to the redesign.
